# Generated by Django 6.0.1 on 2026-02-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
