# Generated by Django 6.0.1 on 2026-02-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_comlaint_alter_feedback_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comlaint',
            new_name='complaint',
        ),
        migrations.AlterModelTable(
            name='complaint',
            table='complaint',
        ),
    ]
