# Generated by Django 6.0.1 on 2026-02-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('studentAge', models.IntegerField()),
                ('studentCity', models.CharField(max_length=40)),
                ('studentEmail', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
